service_homepage:
    path:     /
    defaults: { _controller: DepartementBundle:Service:afficher }
ajouterService:
    path:     /ajout
    defaults: { _controller: DepartementBundle:Service:ajouter }
modifierService:
    path:     /modif
    defaults: { _controller: DepartementBundle:Service:modifier }
supprimerService:
    path:     /supprimer/{id}
    defaults: { _controller: DepartementBundle:Service:supprimer }
