Boutique:
    path:     /
    defaults: { _controller: BoutiqueBundle:Client:RecupererProduit  }
quikview:
    path:     /quikview/{id}
    defaults: { _controller: BoutiqueBundle:Client:quikview }
afficherPanier:
    path:     /afficherPanier
    defaults: { _controller: BoutiqueBundle:Client:afficherPanier }

ValiderAchat:
    path:     /ValiderAchat
    defaults: { _controller: BoutiqueBundle:Client:ValiderAchat }

AnnulerProduit:
    path:     /AnnulerProduit/{id}
    defaults: { _controller: BoutiqueBundle:Client:AnnulerProduit }

Retour:
    path:     /Retour
    defaults: { _controller: BoutiqueBundle:Client:Retour }


search:
    path:     /search
    defaults: { _controller: BoutiqueBundle:Client:search }

pdf:
    path:     /pdf
    defaults: { _controller: BoutiqueBundle:Client:pdf }

delivery:
    path:     /delivery
    defaults: { _controller: BoutiqueBundle:Client:delivery }

statBoutique:
    path:     /stat
    defaults: { _controller: BoutiqueBundle:Client:stat }

setSession:
    path:     /setSession/{id}
    defaults: { _controller: BoutiqueBundle:Client:setProduitToSession }

getSession:
    path:     /getSession
    defaults: { _controller: BoutiqueBundle:Client:getallProduitFromSession }

Checkout:
    path:     /Checkout
    defaults: { _controller: BoutiqueBundle:Client:Checkout }

payment:
    path:     /payment
    defaults: { _controller: BoutiqueBundle:Client:payment }


delsession:
    path:     /delsession/{id}{quantite}
    defaults: { _controller: BoutiqueBundle:Client:delsession }

supprimerpanier:
    path:     /supprimerpanier/{id}
    defaults: { _controller: BoutiqueBundle:Client:supprimerpanier }


delfrompanier:
    path:     /delfrompanier/{id}
    defaults: { _controller: BoutiqueBundle:Client:delfrompanier }

moinscher:
    path:     /moinscher
    defaults: { _controller: BoutiqueBundle:Client:moinscher }

pluscher:
    path:     /pluscher
    defaults: { _controller: BoutiqueBundle:Client:pluscher }

sendSms:
    path:     /sendSms
    defaults: { _controller: BoutiqueBundle:Default:sendSms }