Assurance:
    type: entity
    table: assurance
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        tarif:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
