AssuranceOfferte:
    type: entity
    table: assurance_offerte
    indexes:
        fk_id_assurance4:
            columns:
                - id_assurance
        fk_id_assuranceo:
            columns:
                - id_assurance_o
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idAssurance:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_assurance
        idAssuranceO:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_assurance_o
        dateDebut:
            type: date
            nullable: true
            column: date_debut
        dateFin:
            type: date
            nullable: true
            column: date_fin
    lifecycleCallbacks: {  }
