Constat:
    type: entity
    table: constat
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        noma:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: nomA
        prenoma:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: prenomA
        adressea:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: adresseA
        permisa:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: permisA
        delivrea:
            type: date
            nullable: false
            column: delivreA
        marquea:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: marqueA
        immatriculationa:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: immatriculationA
        choca:
            type: string
            nullable: false
            length: 11
            options:
                fixed: false
            column: chocA
        chocb:
            type: string
            nullable: false
            length: 11
            options:
                fixed: false
            column: chocB
        circonstance1:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        circonstance2:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        circonstance3:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        circonstance4:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        circonstance5:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        circonstance6:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        circonstance7:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        circonstance8:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        circonstance9:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        circonstanceautre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        nomb:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: nomB
        prenomb:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: prenomB
        adresseb:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: adresseB
        permisb:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: permisB
        delivreb:
            type: date
            nullable: false
            column: delivreB
        marqueb:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: marqueB
        immatriculationb:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: immatriculationB
    lifecycleCallbacks: {  }
