Essai:
    type: entity
    table: essai
    indexes:
        fk_id_client:
            columns:
                - id_client
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idClient:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_client
        dateessai:
            type: date
            nullable: false
            column: dateEssai
        etat:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
