InfoPerso:
    type: entity
    table: info_perso
    uniqueConstraints:
        id_client:
            columns:
                - id_client
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        civilite:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        nom:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        prenom:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        dateDeNaissance:
            type: date
            nullable: true
            column: date_de_naissance
        adresse:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        codePostal:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: code_postal
        idClient:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_client
    lifecycleCallbacks: {  }
