Jugement:
    type: entity
    table: jugement
    indexes:
        fk_id_incident:
            columns:
                - id_incident
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idIncident:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_incident
        observation:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        verdict:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
