devis_homepage:
    path:     /devishomepage
    defaults: { _controller: DevisBundle:Default:index }
_ShowR:
    path:     /
    defaults: { _controller: DevisBundle:Devis:ShowAll }
_CreateD:
    path:     /CreateD
    defaults: { _controller: DevisBundle:Devis:create }
_ViewD:
    path:     /ViewD/{id}
    defaults: { _controller: DevisBundle:Devis:view }
_DeleteD:
    path:     /DeleteD/{id}
    defaults: { _controller: DevisBundle:Devis:delete }
_UpdateD:
    path:     /EditD/{id}
    defaults: { _controller: DevisBundle:Devis:update }
_ComboD:
    path:     /ComboD
    defaults: { _controller: DevisBundle:Devis:comb }
_Tri:
    path:     /Tri
    defaults: { _controller: DevisBundle:Devis:Tri }

pdfDevis:
    path:     /pdf/{id}
    defaults: { _controller: "DevisBundle:Devis:pdf" }

recherche_typeDevis:
    path:     /chercherDevis
    defaults: { _controller: "DevisBundle:Devis:chercher" }

_CreateType:
    path:     /CreateType
    defaults: { _controller: DevisBundle:Devis:createType }

_ShowType:
    path:     /ShowTypes
    defaults: { _controller: DevisBundle:Devis:ShowType }