<?php

namespace AppBundle\Repository;

/**
 * SignaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignaleRepository extends \Doctrine\ORM\EntityRepository
{
}
