<?php

namespace BlogBundle\Repository;

use Doctrine\ORM\Query;
use Symfony\Component\HttpFoundation\Request;

/**
 * rechRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rechRepository extends \Doctrine\ORM\EntityRepository
{
    public function rechArticleDQL($author, $title)
    {

        $qb = $this->_em->createQueryBuilder();

        $req = $qb->select('b')
            ->from('UserBundle:Blog', 'b');


        if ($author) {
            $req->Where("b.author like :author");
            $req->setParameter('author', "%" . $author . "%");
        }


        if ($title) {
            $req->andWhere("b.title like :title");
            $req->setParameter('title', "%" . $title . "%");
        }
        return $req->getQuery()->getResult(Query::HYDRATE_OBJECT);

    }

}
