Categorie:
    type: entity
    table: categorie
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nomCategorie:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: nom_categorie
    lifecycleCallbacks: {  }
