Contact:
    type: entity
    table: contact
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        mail:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        etat:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        contenu:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
