Produit:
    type: entity
    table: produit
    indexes:
        fk_categorie:
            columns:
                - id_categorie
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        codeArt:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: code_art
        designation:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        prix:
            type: float
            nullable: false
            precision: 10
            scale: 0
        image:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        quantite:
            type: integer
            nullable: false
            options:
                unsigned: false
    manyToOne:
        idCategorie:
            targetEntity: Categorie
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_categorie:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
