publicite_publicite:
    resource: "@PubliciteBundle/Resources/config/routing/publicite.yml"
    prefix:   /publicite

publicite_homepage:
    path:     /pub
    defaults: { _controller: PubliciteBundle:Default:index }



publicite_json:
    path:     /pubjson
    defaults: { _controller: PubliciteBundle:Default:all }

publicite_jsontrend:
    path:     /pubtrend
    defaults: { _controller: PubliciteBundle:Default:trend }

publicite_jsonpreso:
    path:     /pubperso
    defaults: { _controller: PubliciteBundle:Default:allPerso }

publicite_jsonbyid:
    path:     /pubjsonid/{id}
    defaults: { _controller: PubliciteBundle:Default:byid }

publicite_jsonnew:
    path:     /pubjsonnew
    defaults: { _controller: PubliciteBundle:Default:new }

publicite_jsondelete:
    path:     /pubjsondelete/{id}
    defaults: { _controller: PubliciteBundle:Default:delete }



image_json:
    path:     /imageupload
    defaults: { _controller: PubliciteBundle:Default:uploadImage }

new_user:
    path:     /newuser
    defaults: { _controller: PubliciteBundle:Default:newUser }