forum:
    path:     /
    defaults: { _controller: UserBundle:Default:forum  }
commentArticle:
    path:     /comment/{id}
    defaults: { _controller: BlogBundle:Blog:article }

ajoutcomment:
    path:     /Ajoutcomment
    defaults: { _controller: BlogBundle:Comment:AjoutComment }

modifcomment:
    path:     /Modifcomment
    defaults: { _controller: BlogBundle:Comment:modifier }

suppcomment:
    path:     /Suppcomment/{id}/{blogId}
    defaults: { _controller: BlogBundle:Comment:SuppComment }

ajoutarticle:
    path:     /AjoutArticle
    defaults: { _controller: BlogBundle:Blog:AddArticle }

supparticle:
    path:     /Supparticle/{id}
    defaults: { _controller: BlogBundle:Blog:deleteArticle }

modifarticle:
    path:     /Modifarticle/{id}
    defaults: { _controller: BlogBundle:Blog:update }


bloquerClient:
    path:     /Bloquer/{id}
    defaults: { _controller: BlogBundle:Blog:bloquerClient }


debloquerClient:
    path:     /debloquer/{id}
    defaults: { _controller: BlogBundle:Blog:debloquerClient }


addlikes:
    path:     /likes/{id}
    defaults: { _controller: BlogBundle:Blog:AddLike }

adddislikes:
    path:     /dislikes/{id}
    defaults: { _controller: BlogBundle:Blog:AddDislike }


addview:
    path:     /vue/{id}
    defaults: { _controller: BlogBundle:Blog:AddView }