<?php

namespace DepartementBundle\Repository;

use Symfony\Component\HttpFoundation\Request;

/**
 * domaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialisteRepository extends \Doctrine\ORM\EntityRepository
{
}
