assurance_homepage:
    path:     /
    defaults: { _controller: AssuranceBundle:Default:index }
esprit_test_affiche:
    path:     /Afficher
    defaults: { _controller: AssuranceBundle:Default:Afficher }
esprit_test_supprimer:
    path:     /Supprimer/{id}
    defaults: { _controller: AssuranceBundle:Default:Supprimer }
esprit_test_ajouter:
    path:     /Ajouter
    defaults: { _controller: AssuranceBundle:Default:Ajouter }
esprit_test_modifier:
    path:     /Modifier/{id}
    defaults: { _controller: AssuranceBundle:Default:Modifier }
esprit_test_rechercher:
    path:     /rechercher
    defaults: { _controller: AssuranceBundle:Default:rechercher }
