user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }

showAll:
    path:     /showAllusers
    defaults: { _controller: UserBundle:Default:ShowAllUsers }
showClients:
    path:     /showClients
    defaults: { _controller: UserBundle:Default:ShowClients }
promoteUserExpert:
    path:     /PromoteUserExpert/{id}
    defaults: { _controller: UserBundle:Default:PromoteUserExpert }
promoteUserEmploye:
    path:     /PromoteUserEmploye/{id}
    defaults: { _controller: UserBundle:Default:PromoteUserEmploye }
showExpert:
    path:     /ShowExpert
    defaults: { _controller: UserBundle:Default:ShowExpert }
ShowEmploye:
    path:     /ShowEmploye
    defaults: { _controller: UserBundle:Default:ShowEmploye }
