forum_homepage:
    path:     /index
    defaults: { _controller: ForumBundle:Default:index }

add_form:
    path:     /add
    defaults: { _controller: ForumBundle:Default:add }


detailsF:
    path:     /details/{id}
    defaults: { _controller:ForumBundle:Default:details}

modifierF:
    path:     /modifier/{id}
    defaults: { _controller:ForumBundle:Default:modifier}

supprimerF:
    path:     /supprimer/{id}
    defaults: { _controller:ForumBundle:Default:supprimer}

reclamerF:
    path:     /reclamer/{id}
    defaults: { _controller:ForumBundle:Default:reclamer}

afficherRec:
    path:     /reclamations/{id}
    defaults: { _controller:ForumBundle:Default:afficherRec}


mesForums:
    path:     /mesforums/{id}
    defaults: { _controller:ForumBundle:Default:mesForums}

participe:
    path:     /participe
    defaults: { _controller:ForumBundle:Default:participe}
chart:
    path:     /chart
    defaults: { _controller: "ForumBundle:Default:chart" }



back_forum:
    path:     /backforum
    defaults: { _controller: ForumBundle:Default:back  }
    methods:  [GET, POST]

validPub:
    path:     /{id}/valideArticle
    defaults: { _controller: ForumBundle:Default:valider }
    methods:  [GET, POST]

refusPub:
    path:     /{id}/refusArticle
    defaults: { _controller: ForumBundle:Default:refuser }
    methods:  [GET, POST]