<?php

namespace BoutiqueBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    function findDQL($libelle, $categorie, $prix)
    {

        $qb = $this->_em->createQueryBuilder();

        $req = $qb->select('p')
            ->from('UserBundle:Produit', 'p')
            ->join('p.categorie', 'c');


        if ($libelle) {

            $req->Where("p.libelle like :libelle ");
            $req->setParameter('libelle', "%" . $libelle . "%");

        }


        if ($categorie) {
            $req->andWhere("c.libelle like :libelle ");
            $req->setParameter('libelle', "%" . $categorie . "%");
        }


        if ($prix) {
            $req->andWhere("p.prix BETWEEN :prix-20 AND :prix+20");
            $req->setParameter('prix', $prix);
        }


        return $req->getQuery()->getResult();

    }

    function triermoinsDQL()
    {
        $query = $this->getEntityManager()
            ->createQuery("
            select p from UserBundle:Produit p
            order by p.prix ");


        return $query->getResult();


    }

    function trierplusDQL()
    {
        $query = $this->getEntityManager()
            ->createQuery("
            select p from UserBundle:Produit p
            order by p.prix  DESC ");


        return $query->getResult();


    }
}
