<?php

namespace BoutiqueBundle\Repository;

/**
 * ratingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ratingRepository extends \Doctrine\ORM\EntityRepository
{

    public function AVGRating()
    {
        $query = $this->getEntityManager()
            ->createQuery("select c.produit, AVG (c.rating) from 
         UserBundle:rating c GROUP BY c.produit"
            );
        return $query->getResult();
    }
}
