Paiement:
    type: entity
    table: paiement
    indexes:
        fk_client_fac:
            columns:
                - id_client
        fk_devis_fac:
            columns:
                - id_devis
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idClient:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_client
        idDevis:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_devis
        paid:
            type: integer
            nullable: false
            options:
                unsigned: false
        total:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
