Participation:
    type: entity
    table: participation
    indexes:
        fk_id_event:
            columns:
                - id_evenement
        fk_id_participant:
            columns:
                - id_participant
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idEvenement:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_evenement
        idParticipant:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_participant
        qrcode:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: QrCode
        etat:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: Etat
    lifecycleCallbacks: {  }
