Reclamation:
    type: entity
    table: reclamation
    indexes:
        fk_reclamation_client:
            columns:
                - id_client
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        objet:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        contenu:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        type:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        etat:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        reponse:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        date:
            type: date
            nullable: true
    manyToOne:
        idClient:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_client:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
