Reduction:
    type: entity
    table: reduction
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        taux:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
