TypeAssurance:
    type: entity
    table: type_assurance
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        champ1:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        champ2:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        champ3:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        champ4:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        critere1:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        devis1:
            type: integer
            nullable: false
            options:
                unsigned: false
        critere2:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        devis2:
            type: integer
            nullable: false
            options:
                unsigned: false
        critere3:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        devis3:
            type: integer
            nullable: false
            options:
                unsigned: false
        critere4:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        devis4:
            type: integer
            nullable: false
            options:
                unsigned: false
        prixInitial:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: prix_initial
    lifecycleCallbacks: {  }
