admin_actualite_index:
    path:     /
    defaults: { _controller: "GarantiaBundle:Actualite:index" }
    methods:  GET

admin_actualite_show:
    path:     /{id}/show
    defaults: { _controller: "GarantiaBundle:Actualite:show" }
    methods:  GET

admin_actualite_new:
    path:     /new
    defaults: { _controller: "GarantiaBundle:Actualite:new" }
    methods:  [GET, POST]

admin_actualite_edit:
    path:     /{id}/edit
    defaults: { _controller: "GarantiaBundle:Actualite:edit" }
    methods:  [GET, POST]

admin_actualite_delete:
    path:     /{id}/delete
    defaults: { _controller: "GarantiaBundle:Actualite:delete" }
    methods:  DELETE
