departement_homepage:
    path:     /
    defaults: { _controller: DepartementBundle:Departement:afficher }
ajouterDepartement:
    path:     /ajout
    defaults: { _controller: DepartementBundle:Departement:ajouter }
modifierDepartement:
    path:     /modif
    defaults: { _controller: DepartementBundle:Departement:modifier }
supprimerDepartement:
    path:     /supprimer/{id}
    defaults: { _controller: DepartementBundle:Departement:supprimer }
